### ISSUE TITLE
Facebook comments module

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxmedia/redaxscript#100]
As an alternative option to native Redaxscript comments you may enable facebook comments plugin to raise your content and bring some "life" to your webpage.

no iframe, but with facebook API

more informations:
https://developers.facebook.com/docs/plugins/comments
http://stackoverflow.com/questions/6796930/programmatically-posting-facebook-comments

**Comment by redaxmedia** [comment]
Closed - lack of time...
