### ISSUE TITLE
Conditional display of breadcrumbs and extras (aside) depending on page

### ISSUE THREAD

**Issue by NetLancer** [redaxmedia/redaxscript#237]
trying to make breadcrumbs display on pages but not homepage, construction:
if !is_front_page() {echo breadcrumbs()} seems no good, and same setting needed for extras(). Please help, I'm new to redaxscript and php amateur ))

**Comment by redaxmedia** [comment]
No problem,

you can use the deprecated PHP constants like:

<pre>if (!FULL_ROUTE) {...}</pre>

or the registry class like:

<pre>if (!Redaxscript\Registry::get('fullRoute')) {...}</pre>

Please reopen this issue, if this anwser doesn't provide enough information.

**Comment by NetLancer** [comment]
clear, thanks

**Comment by redaxmedia** [comment]
Great, please consider to give Redaxscript a star on Github :-)
