### ISSUE TITLE
Article alias must contain letter

### ISSUE THREAD

**Issue by JimMorrison723** [redaxmedia/redaxscript#238]
Article alias must contain at least 1 letter, it can't be only numbers.
I don't know if it's a bug or feature (i think Validator Alias bug),
but it would be good if we can use only numbers in article  alias.

**Comment by redaxmedia** [comment]
Redaxscript is using numbers for the pagination like <code>category-with-sub/2</code> .. for this reason number only articles are not allowed because this would need extra smart code.
