### ISSUE TITLE
Better module install verification

### ISSUE THREAD

**Issue by JimMorrison723** [redaxmedia/redaxscript#239]
If module alias contains space character, it will say successfully installed, but not.

**Comment by redaxmedia** [comment]
Thank you for reporting, is this related to release 2.2.0?

**Comment by JimMorrison723** [comment]
Sorry, yes, 2.2.0.

**Comment by redaxmedia** [comment]
I will take a look on it...

**Comment by redaxmedia** [comment]
This affects deprecated codebase in <code>admin_query.php</code>, I will not touch this until I refactor the whole admin. You posted a valid issue, but for now I have to close it.

Sorry for that, but I have to focus on the milestones to move Redaxscript forward to OOP.
