### ISSUE TITLE
Website relaunch

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#245]
1. Top Navigation
 * Download
 * Wiki
 * Chat

1. Story telling
1. Feature telling

**Comment by joergsteinhauer** [comment]
what do you mean with facebook and github integration?

**Comment by redaxmedia** [comment]
1. Facebook group page
1. Facebook group - latest question on the homepage?
1. Github milestone and issue page

**Comment by redaxmedia** [comment]
Closed - not a technical issue
