### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by NodexTech** [redaxmedia/redaxscript#256]
In your functions (php) (includes/Parser.php) you try to block dangerous functions but you forgot the back-tick operator (`), you might want to check if the first and last char in the function match that and return out of it.

To be honest it's really dangerous letting people call functions with just a blacklist, my advice is to blacklist EVERYTHING and maintain a whitelist

**Comment by redaxmedia** [comment]
I know this is dangerous but:

1. This is only allowed to admins
1. Must be a valid JSON format, the back-tick operator will cause a failure and therefore not be called

**Comment by NodexTech** [comment]
This is not a good approach to security.

There are many other holes I have found in your CMS, best of luck for the future.

**Comment by redaxmedia** [comment]
You are free to drop me a mail to info@redaxmedia.com for other security issues.

**Comment by NodexTech** [comment]
It's fine, I will release them publicly so people can fix them and be aware.

Again best of luck with your project

**Comment by redaxmedia** [comment]
Keep in mind not to test again XSS with admin / account with disabled XSS filtering.
