### ISSUE TITLE
Bug... Incorrect use of $_SERVER['https'] should be upper case

### ISSUE THREAD

**Issue by nigel-moore** [redaxmedia/redaxscript#260]
Bug...
includes/get.php
Line 182
$protocol = $_SERVER['https'] ? 'https' : 'http';
should be uppercase...
$protocol = $_SERVER['HTTPS'] ? 'https' : 'http';

**Comment by redaxmedia** [comment]
Resolved in the develop branch, there is a new abstract Server class that contains a Protocol class:

https://github.com/redaxmedia/redaxscript/blob/develop/includes/Server/Protocol.php
