### ISSUE TITLE
Add close button for gallery

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxmedia/redaxscript#261]
For beter user experience und usability we need a close button for the gallery module. In some cases user don't know how to close a gallery especially on mobile devices. 

Further we need a responsive design for the whole module, so it can be easily used on every device (in this case I already developed some designs, e.g. http://joergsteinhauer.net/ - maybe we could use this CSS)

**Comment by redaxmedia** [comment]
No problem, how should the close button look like?

**Comment by joergsteinhauer** [comment]
Simple as possible. I think just an x-icon. I could do some styling stuff.

**Comment by redaxmedia** [comment]
Merged with issue: https://github.com/redaxmedia/redaxscript/issues/276
