### ISSUE TITLE
Problem with alignment of gallery loader

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxmedia/redaxscript#262]
1. Disable preload function in mobule gallery startup.js 
```preload: false```
2. see how the loader element will be aligned to the whole window - it apperas in the top left corner 
3. it happens, because the gallery DIV is empty and has no width/height while loading image and other stuff. after that js triggers and add some inline css (margin)

![_2015-03-06_22-56-32](https://cloud.githubusercontent.com/assets/1843754/6537201/a95bb10e-c454-11e4-8040-b0ddd8d5d9ff.png)

**Comment by redaxmedia** [comment]
1. Okay, or maby another strategy for preloading like only current visible gallery?
2. Please try to reproduce the aligment issue on the default template! I we should move to position: fixed like for the controls...
3. Maby, but it worked someday

To sum this up, this is a issue that can easy be resolved by you inside a sperated bugfix branch :-) Added to Milestone 2.4.0

**Comment by joergsteinhauer** [comment]
1. Nice idea! In most cases it would lead the user to let preloader enabled. So there would no need to have an preloader after clicking a thumb-image (like in my screenshot)
2. I tried it on my template, there is no difference to default.template in this case. Also teid with ```position:fixed```
3. yes, I also didn't have any problems till now...

Maybe we need an extra container for preloader (not an pseudo-element on the gallery-div), which we could positioned like Nolte.
Of course, I can do it in an extra branch. But in this case we need some js modifications, which should at least checkt by you. 
I hope I can start with this issue next weeks...

**Comment by redaxmedia** [comment]
I cannot see a alignment issue under Firefox and Chrome

http://develop.redaxscript.com/gallerytest

Sorry, but I have to close this issue unless you tell me how to reproduce it.
