### ISSUE TITLE
tag or label feature

### ISSUE THREAD

**Issue by 107w** [redaxmedia/redaxscript#263]
I've read the wiki and some of the documents but cannot figure out information about this kind of feature.Redaxscript is a lighting fast cms for blog with user permissions control so I wonder if I can tag or label an article.Thank you~

**Comment by redaxmedia** [comment]
They is only a keyword field at the moment, please discuss this feature request inside our facebook group. The current state of the Redaxscript development is a feature freeze: https://github.com/redaxmedia/redaxscript/wiki/Development but we can still talk about new things that are wanted by many users.

**Comment by redaxmedia** [comment]
Closed, please discuss this on facebook group
