### ISSUE TITLE
SQLite install security

### ISSUE THREAD

**Issue by halojoy** [redaxmedia/redaxscript#294]
I have used sqlite a lot before. There are some issues. Sqlite database is stored in a plain readable file. The name is random. Extension can be anything or no extension at all.

When I installed redaxscript first time, I did not enter any database name for sqlite. The result is it was named 'localhost' and location was root of website. When browsing anyone can download and/or read this file. TOTALLY  unsecure!

I suggest the installscript should ALWAYS add an extension. And that this extension is protected by .htaccess.
I suggest a commonly used extensioon: db3
3 is for it is created by SQLite 3.x.x.x
In PHP 5.6.5 the sqlite version is now 3.8.7.2.

.htaccess change:

filesmatch \.(php|phtml|db3)$
	deny from all
/filesmatch

I also suggest a default database name: redaxcms
And that it is stored in folder 'database'
This means a default full name path:

database/redaxcms.db3

Greetings, Stefan

**Comment by redaxmedia** [comment]
Hey,

this was my first time with SQLite and of course you are totally right with your suggestions.

1. I will add a random generated name + db3 extention
2. I will add db3 to deny from all

**Comment by halojoy** [comment]
An alternative I have seen used, is to let the one who is installaling choose a name for the file. 
Then protect this name written in .htaccess.
Question is where to put the database file.
My suggestion is inside the /database/ folder.

**Comment by redaxmedia** [comment]
I prefer the first method, watch out for the develop branch once I closed the issue.

**Comment by halojoy** [comment]
Okay. I also find first method good.

**Comment by redaxmedia** [comment]
Done with https://github.com/redaxmedia/redaxscript/commit/d987c75435b9431db80b0cc7949e91fc4d19eeca

Checkout the develop branch and tell me if this works for you!
