### ISSUE TITLE
ORM.php missing in DEVELOP branch

### ISSUE THREAD

**Issue by halojoy** [redaxmedia/redaxscript#295]
The folder 'libraries' and the file ORM.php
is missing in the develop branch.
So the install script does not work. When trying develop.

Actually ORM.php is missing from the
- master
- heroku
- tag 2.4.0
- tag 2.3.0

It is missing everywhere in Github code.
But in the download of 2.4.0 it is there. And works.

**Comment by redaxmedia** [comment]
You have to fetch the PHP dependencies using composer^^

https://github.com/redaxmedia/redaxscript/wiki/Composer-guide
