### ISSUE TITLE
Not working behind HTTPS proxy

### ISSUE THREAD

**Issue by EtienneBruines** [redaxmedia/redaxscript#303]
When running Redaxscript (as HTTP apache2/php), behind a HTTPS proxy (so only one application listens to HTTPS port), it does not work. 

# Why
Because Redaxscript defines URLs all absolute: `http://www.example.local/`

Modern browsers refuse to load HTTP elements when connected through HTTPS. 

# Solution
It would help if resources would be referenced by `/resouces/image.jpg`, instead of `http://www.example.local/resources/image.jpg`. 

It would also help if the protocol / method was omitted, resulting in `//www.example.local/resources/image.jpg`.

**Comment by redaxmedia** [comment]
Is this issue still valid? Redaxscript does analyse the protocol and is using <code>http://<code> or <code>https://</code> as needed.

Did you run the testing suite using PHPUnit on your machine?

Tags like links, scripts and iframes should allready use the protocol relative urls. Can you give me a more accurate report?

**Comment by EtienneBruines** [comment]
Behind a proxy, redaxscript isn't able to guess correctly whether it should use `http` or `https` - I don't see how it could do that correctly. This was the first/only solution that came to mind.

I will need a moment to test this for the `master` branch. This was valid for the latest stable download. I'll post more info in a minute.

**Comment by redaxmedia** [comment]
All right, take your time. You are familar with PHPUnit?

https://github.com/redaxmedia/redaxscript/wiki/Local-testing#utilize-grunt

**Comment by EtienneBruines** [comment]
I'm getting a `Fatal error: Class 'ORM' not found in /var/www/public/includes/Db.php on line 43` message when using the `master` branch (after enabling error reporting). 

Not familiar with PHPUnit, but seeing those guides, I could use it if you'd like.

**Comment by redaxmedia** [comment]
You have to use "composer install" to fetch the dependencies...

**Comment by redaxmedia** [comment]
I can teach you all the stuff, no problem... ah, btw. it would be great if you give Redaxscript a star :-)

**Comment by EtienneBruines** [comment]
I hate to bother you with it, but following your guide, doesn't work out
as planned.

*root@huperwebs (/tmp/redaxscript) # php composer.phar install*
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> php -r "is_dir('libraries') || mkdir('libraries');"
> php -r "copy('vendor/j4mie/idiorm/idiorm.php', 'libraries/ORM.php');"
*root@huperwebs (/tmp/redaxscript) # grunt phpunit            *
Running "phpunit:development" (phpunit) task
Starting phpunit (target: development) in tests/includes
SQLite - Fatal error: Command failed: PHP Fatal error:  Uncaught
exception 'PDOException' with message 'could not find driver' in
/tmp/redaxscript/vendor/j4mie/idiorm/idiorm.php:255
Stack trace:
#0 /tmp/redaxscript/vendor/j4mie/idiorm/idiorm.php(255):
PDO->__construct('sqlite:', NULL, NULL, NULL)
#1 /tmp/redaxscript/vendor/j4mie/idiorm/idiorm.php(388):
ORM::_setup_db('default')
#2 [internal function]: ORM::raw_execute('DROP TABLE IF E...')
#3 /tmp/redaxscript/vendor/j4mie/idiorm/idiorm.php(2205):
call_user_func_array(Array, Array)
#4 /tmp/redaxscript/includes/Installer.php(271):
ORM::__callStatic('rawExecute', Array)
#5 /tmp/redaxscript/includes/Installer.php(271):
Redaxscript\Db::rawExecute('DROP TABLE IF E...')
#6 /tmp/redaxscript/includes/Installer.php(64):
Redaxscript\Installer->_rawExecute('drop', 'sqlite')
#7 /tmp/redaxscript/tests/bootstrap.php(61):
Redaxscript\Installer->rawDrop()
#8 /tmp/redaxscript/vendor/phpunit/phpunit/src/Util/Fileloader.php(58):
include_once('/tmp/redaxscrip...')
#9 /tmp/redaxscript/vendor/phpunit/phpunit/src/Util/Fileloader.php(42):
in /tmp/redaxscript/vendor/j4mie/idiorm/idiorm.php on line 255

Something with SQLite driver not being found. Perhaps it's not being
fetched with composer?

**Comment by EtienneBruines** [comment]
Another thing that failed, after running `composer install`, as you
suggested, did not fix the error ` *Fatal error*: Class 'ORM' not found
in */var/www/public/includes/Db.php* on line *43`.
*

**Comment by redaxmedia** [comment]
The best would be a chat, join me on gitter - it is some kind of IRC

Webchat: https://gitter.im/redaxmedia/redaxscript

**Comment by redaxmedia** [comment]
Closed for now, please open another issue if the problem is still present.
