### ISSUE TITLE
Redaxscript example site, missing protocol scheme

### ISSUE THREAD

**Issue by EtienneBruines** [redaxmedia/redaxscript#307]
`database/html/extras/footer.phtml`
contains
`<a href="//redaxscript.com/download/releases" title="Releases">Releases</a>`

Which is nice, for HTTP websites. But when a site is served over HTTPS, as "it should", it fails - because https://redaxscript.com does not have a valid SSL certificate. 

# Fix possibility 1
Change it explicitly to `http://redaxscript.com`

# Fix possibility 2
Make redaxscript.com available via HTTPS.

**Comment by redaxmedia** [comment]
Thank you for find this. You are totally right, protocol relative urls should not be used within anchors, only within links, scripts and iframes that include files / content from another domain.

However, I quickly fixed it inside the master. https://github.com/redaxmedia/redaxscript/commit/168cf4a221d4f823201e21c802ae9bcc56b0117e
