### ISSUE TITLE
Unable to access login panel

### ISSUE THREAD

**Issue by cgkh** [redaxmedia/redaxscript#309]
I am trying out Redaxscript for the first time.

I have downloaded redaxscript_2.4.0_lite.zip.

Unzipped locally an uploaded to my vps.

VPS config is:

debian 7
mysql Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (i686) using readline 6.2
PHP 5.4.41-0+deb7u1 (cli) (built: May 28 2015 18:22:26)
nginx version: nginx/1.2.1

I have proceeded with the installation as per the instructions:

https://github.com/redaxmedia/redaxscript/wiki/Installation-guide

The table appear to be created correctly in the mysql database.as follows

| llarticles          |
| llcategories        |
| llcomments          |
| llextras            |
| llgroups            |
| llmodules           |
| llsettings          |
| llusers    

When I browse to the website http://linuxli.eu, the index.php is served with not problem..

However, when I click on Login (http://linuxli.eu/login) nothing happens. No login panel or page is served.

The installation is located on the server one directory down in public_html

I have has a look at the code and am stumped.

I do not use facebook.

Would appreciate some feedback on what may be wrong.

**Comment by redaxmedia** [comment]
Hello and welcome to Redaxscript.

It looks like an issue with the mod_rewrite Module. Try one of the following troubleshootings:
https://github.com/redaxmedia/redaxscript/wiki/Troubleshooting#rewrite-issue

Consider to give Redaxscript a star on Github, if you really like it. Thank you
