### ISSUE TITLE
Support for Facebook's open graph images

### ISSUE THREAD

**Issue by joergsteinhauer** [redaxmedia/redaxscript#330]
For better and dynamic Facebook image preview controll, we need an extra input field in admin.
![rxs_og](https://cloud.githubusercontent.com/assets/1843754/9833236/0ade9146-5990-11e5-873d-8f3329631693.jpg)

It would allow inserting custom URL's to images in particular article, which would alert in a meta-tag in the `<head>` section. Multiple URL's could be inserted with comma as separator (another similar solution is also possible, for example multiple input fields).

Example:
Adding `http://domain.com/image.jpg` in the input field would insert following meta-tag just right before closing `</head>` tag:
```html
<meta property="og:image" content="http://domain.com/image.jpg" />
```

It could be implemented as core functionality or as a module.

Read more about open graph https://developers.facebook.com/docs/sharing/webmasters#markup

**Comment by redaxmedia** [comment]
I have out of the box solution for that problem because I will not add another field to the database table just for facebook.

Please define custom meta tags inside head.phtml of your template.
