### ISSUE TITLE
Editor module - URL Insert

### ISSUE THREAD

**Issue by Capt-Zeanie** [redaxmedia/redaxscript#353]
I have just installed 2.5.0 FULL from the main website.

I enabled the Editor Module in Admin

I create a new Article, in the textarea for the main I highlighted a word in the article text and then pressed the Insert Link button in the Editor. I typed in a URL and press OK

I expect to see the highlighted word be converted into URL but it does not happen.
What does happen is the the URL is inserted at the beginning of the text article textarea as
eg <a href="xx.xxx" title="xx.xxx">xx.xxx</a> without the highlighted word being the url description

I then tried just placing the cursor anywhere in the textarea and  and then pressed the Insert Link button in the Editor. I typed in a URL and press OK

I expect to see the the URL be placed where the cursor was but it does not happen.
What does happen is the the URL is inserted at the beginning of the text article textarea as
eg <a href="xx.xxx" title="xx.xxx">xx.xxx</a>

It would appear that the javascript function to insert the URL is prepending the url at the start of the textarea.

The url is inserted at the begining of the text and not where the cursor was before insert link was

**Comment by redaxmedia** [comment]
Redaxscript's editor module is many years old and was developed by myself, there are better third party WYSIWYG editors nowdays. This is a known bug that will not be fixed.

Redaxscript 3.0.0 will contain a fresh Ckeditor module :
https://github.com/redaxmedia/redaxscript/issues/347
