### ISSUE TITLE
Editor module - Insert Video into Article

### ISSUE THREAD

**Issue by Capt-Zeanie** [redaxmedia/redaxscript#354]
I have tried registering on the main redaxscript forum twice now 24hrs ago but I don't get a confirmation email so I am writing the issue here that I would like a hopeful answer.

When I creating an article, how do you embed a youtube video. I tried all the usual way from an iframe, url link (see my other issue on urls) or any other way.

On other CMS the parser with convert the BBC embed code to the necessary html but I can see how this happens on redaxscript.

For example how would I insert the youtube video url=http://www.youtube.com/watch?v=J30WJfeH2_4 in an article in a way that when the article is shown to the user the video is visable and playable

Thank you

**Comment by redaxmedia** [comment]
Sorry for the delay, I just confirm the registration in the forum.

Redaxscript's editor module is many years old and was developed by myself, there are better third party WYSIWYG editors nowdays. Such a feature will never be developed.

You can use plain HTML using the iframe tag, switch to the editor's source mode before you enter it.

Redaxscript 3.0.0 will contain a fresh Ckeditor module: #347
