### ISSUE TITLE
Lost with install on PDO errors

### ISSUE THREAD

**Issue by ParkerFoto** [redaxmedia/redaxscript#356]
Hi,

I have just about died every thing to resolve this and so now I seek help.  Only getting white screen of death.  Here is the error from the log.  

 PHP Fatal error:  Class 'ORM' not found in /var/www/html/includes/Db.php on line 43

My environment:
New install on Debian Jessie (8.2.0).  mariaDB (mysql) installed and running.  php5 installed and php_info test ok.

mysql PDO  installed as per php info below:
etc/php5/apache2/conf.d/05-opcache.ini, /etc/php5/apache2/conf.d/10-mysqlnd.ini, /etc/php5/apache2/conf.d/10-pdo.ini, /etc/php5/apache2/conf.d/20-curl.ini, /etc/php5/apache2/conf.d/20-intl.ini, /etc/php5/apache2/conf.d/20-json.ini, /etc/php5/apache2/conf.d/20-mysql.ini, /etc/php5/apache2/conf.d/20-mysqli.ini, /etc/php5/apache2/conf.d/20-pdo_mysql.ini, /etc/php5/apache2/conf.d/20-pdo_sqlite.ini, /etc/php5/apache2/conf.d/20-readline.ini, /etc/php5/apache2/conf.d/20-sqlite3.ini, /etc/php5/apache2/conf.d/20-tidy.ini

Any assistance would be greatly appreciated.  I cannot paste a link to the server as it is internal facing only.

Regards,

Mark

**Comment by redaxmedia** [comment]
Hello,

please use the official download from the website that contains the folder <code>libraries</code> with the file <code>ORM.php</code>.

Using the source from GitHub needs an <code>composer install</code> to fetch the third party depedencies like the ORM.

**Comment by ParkerFoto** [comment]
Fixed.  Thank you

**Comment by redaxmedia** [comment]
Thank us with a star for Redaxscript :-)
