### ISSUE TITLE
Shortcuts conflict in Polish

### ISSUE THREAD

**Issue by AlekSet** [redaxmedia/redaxscript#366]
Those shortcuts makes conflicts with Polish keyboard (Polish programmer):
CLTR+ALT+C
CLTR+ALT+S
CLTR+ALT+L

In Polish letters C S L used with right ALT gives letters: Ą Ś Ł.
No matter whitch shortcut I use (CLTR+ALT+ or Right ALT+) always they perform actions that are assigned to them in the script and it is not possible to enter Polish letters.

**Comment by redaxmedia** [comment]
You can override the keycodes inside the <code>init.js</code> of your template:
https://github.com/redaxmedia/redaxscript/blob/master/templates/default/scripts/init.js

Here is a overview of the base <code>init.js</code>:
https://github.com/redaxmedia/redaxscript/blob/master/scripts/init.js#L165-L172

Use the following Javascript code, replace {name} and {number} as needed:
<pre>
rs.plugins.keyShortcut.options.keyCode.{name} = {number};
</pre>

Find the right keycode:
http://isithackday.com/whatkeycode

**Comment by AlekSet** [comment]
When add i.e.
```rs.plugins.keyShortcut.options.keyCode.{log} = {49};```
to `init.js` in other template then default it not work at all.
When added in default template, it prints in page source but not work, admin menu not dropping down.
Cleaning browser cache not helping.

**Comment by redaxmedia** [comment]
You have to write valid Javascript... without the { and } :-)

**Comment by AlekSet** [comment]
I should go to sleep instead of taking up for this job. I made a mistake in spelling in other place and hence the problem with action.
However, still only works when it is entered in the template default. In another template is not working.

**Comment by redaxmedia** [comment]
It only works for the default template because you set inside templates/default/scripts/init.js... if you want this feature in your customized template than edit related file like  templates/{custom}/scripts/init.js

**Comment by AlekSet** [comment]
Again, my oversight. Of course, I added an entry in the file ``init.js`` of new template, but did not change the path to the script in file ``.loader``. Mea culpa, stupido ;-p

**Comment by redaxmedia** [comment]
Great!
