### ISSUE TITLE
Theme/plugin installer

### ISSUE THREAD

**Issue by JimMorrison723** [redaxmedia/redaxscript#383]
I think we can agree, that a wordpress like 'Theme directory' (same with extensions) would give a big push to this cms. It 'just' needs a webpage, where people can upload themes, extensions, to showcase their work.
From CMS side, it needs an admin plugin, that would take information from the showcase site (through json api for example), to be able to download the given ZIP files from the server, and then run a PHP script that unpacks the folder to modules/templates.
The hard part is making a webpage (maybe there is a solution out there for it), creating a module that makes is possible to browse it through a redaxscript powered website is ain't too hard (as i see). Once a beta showcase site is done, i could do the plugin for it (so i'm not just about giving ideas, but helps you make it happen).
Sooner or later it will happen, i know (I hope :)).

**Comment by redaxmedia** [comment]
Hello Jim,

thank you for your request - I like the idea. At the moment we are focusing on the Redaxscript 3.0.0 development and later on the website relaunch. Maby you can image how time consuming this is with a very small developer base. For that reason, I have to close this issue - we can talk about ideas and suggestion in our forum, this is a better place.

Let me know if you like to join Redaxscript 3.0.0, we seriously need some help.

**Comment by JimMorrison723** [comment]
Absolutely! I'm looking the issues with milestone 3.0.0 right now. Yeah, i think i can help you guys out a little. Maybe i'll need a little time to catch up, but expect some pull requests from me on the next week!

**Comment by redaxmedia** [comment]
Drop me a line to talk about joining the development: info@transcript.com
