### ISSUE TITLE
Installation on subdomain with subdirectory

### ISSUE THREAD

**Issue by graphicomputer** [redaxmedia/redaxscript#384]
I assume the issue I'm having is because of the .htaccess file - ive tried a number of options but still unable to install - I admit I'm completely lost with .htaccess files!

I'm trying to install redax (currently for trialling) as I'm looking for a cms to replace an existing one...

currently (for testing) I'm trying to install at development.graphicomputer.com/redax but just get a combo of page not found & unable to connect to db issues.

I'm happy to send on files etc if you need

**Comment by redaxmedia** [comment]
Hello, have you tried our troubleshooting?https://github.com/redaxmedia/redaxscript/wiki/Troubleshooting

**Comment by redaxmedia** [comment]
I guess, this worked for you!? Consider to give Redaxscript a star :-)
