### ISSUE TITLE
Remote posting via console

### ISSUE THREAD

**Issue by Axisar** [redaxmedia/redaxscript#419]
Is there any way to make remote posts? like in wordpress via xmlrpc, for example.

**Comment by redaxmedia** [comment]
Hello,

there is no way to post contents remotely at the moment. I'm currently working on a Console component for Redaxscript 3.0.0 that could be extended with a "post" Command. Unfortunately, I need to focus on the 3.0.0 milestone to get the release finished this year.

Consider to give me a helpful hand on a console post command if you like to have that feature in Redaxscript 3.0.0 - there is also a webconsole you can play around, start with help first:http://develop.redaxscript.com/secret/console.php
