### ISSUE TITLE
Bug in Controller\Install - Detector\Language always returns en

### ISSUE THREAD

**Issue by SprintSerwis** [redaxmedia/redaxscript#435]
In section:
`/\* install and mail */

```
    if ($this->_install($adminArray) && $this->_mail($adminArray))
    {
        return $this->_success(
        [
            'url' => $this->_registry->get('root'),
            'message' => $this->_language->get('installation_completed')
        ]);
    }
    return $this->_error(
    [
        'message' => $this->_language->get('installation_failed')
    ]);`
```

$this->_language->get() gets only the text from a file en.json, also then the 

<pre>$_SERVER["HTTP_ACCEPT_LANGUAGE"] is 'pl'</pre>

I wanted to fix it, but I do not know how.

**Comment by redaxmedia** [comment]
Thank you for reporting, I can confirm this bug and just added it to the 3.0.0 milestone.

**Comment by redaxmedia** [comment]
Issue solved, there was an Language->init() inside the Installer class that caused a switch to the english language.
