### ISSUE TITLE
Mobile / offcanvas menu optimization

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#450]
There are various issues with a mobile / offcanvas menu that is using <code>position: fixed</code>, therefore we need to switch to a <code>position: absolute</code> approach.

### Actual

- The menu and the page are scrolling separately
- Scrolling the page is causing a flicker on browser's that remove the top-bar
- The amount of entries is limited to the viewport, so it cannot handle 100 entries for example
- The desktop version does not work with more than 2 entries

### Target

- Menu and page are scrolling together
- Menu can have unlimited amount of entries
- The Desktop version should not break if more than 2 entries

### Todo

1. Switch to <code>position: absolute</code> and use a menu wrapper over the whole page with <code>position: relative</code>
1. Remove the admin hack, this should no longer be needed
1. Fix the issue that menu is always visible under iOS8
1. Use nth-child to hide more than 2 entries on the Desktop version between small and large - overflow: hidden was removed because this breaks the sub-menu to appear on hover

<pre>
> li:nth-child(3n+1)
{
	display: none;
}
</pre>

Inspiration:
http://foundation.zurb.com/sites/docs/v/5.5.3/components/offcanvas.html

**Comment by joergsteinhauer** [comment]
better use this one for inspiration http://codepen.io/ncerminara/full/KJjiD/

**Comment by redaxmedia** [comment]
Done
