### ISSUE TITLE
Visual update for the byline

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#452]
The byline should be more prominent and needs a visual update. Pure text without icons is too boring.

Following image is just an idea / concept:

![](https://i.snag.gy/wmKXW7.jpg)

**Comment by joergsteinhauer** [comment]
please check my first attempt. any ideas?

![rxs byline](https://cloud.githubusercontent.com/assets/1843754/20686109/930b93dc-b5b7-11e6-83ef-d2e710650b89.png)

**Comment by redaxmedia** [comment]
Typo and position of the icons never reached a final version, I have to close this issue because it is wasting our time.
