### ISSUE TITLE
How do I add read more button

### ISSUE THREAD

**Issue by eArabic** [redaxmedia/redaxscript#476]
Hello thank you very much, he is very excellent and fast and light.
How do I add read more button.

![333](https://cloud.githubusercontent.com/assets/24383546/21470839/166e6b66-caab-11e6-891e-9c40eb20c46a.png)

**Comment by redaxmedia** [comment]
Just add `<readmore>` - thats it...

Documentation: http://redaxscript.com/documentation/contents/pseudo-tags

**Comment by eArabic** [comment]
Thank you very much, it has been Redaxscript a star.
