### ISSUE TITLE
Bug writing comment with a user author in arabic

### ISSUE THREAD

**Issue by eArabic** [redaxmedia/redaxscript#477]
There is a problem in writing the New comment with a user name in Arabic Author ...
When you are writing a comment as a user in the Arabic language as an error message in the attached picture show.

![100000](https://cloud.githubusercontent.com/assets/24383546/21471224/8576108a-cabb-11e6-968c-3b85efe53ff3.png)

![010101](https://cloud.githubusercontent.com/assets/24383546/21471226/897b7896-cabb-11e6-8827-784b1186d76b.png)

**Comment by redaxmedia** [comment]
Thank you for reporting. Please post the example wording here, so I can test again it.

**Comment by eArabic** [comment]
Thank you very much, this text can play test yourself.

 **Author:** محمد
**Text :** تجربة كتابة مقالة ... تجربة كتابة مقالة ...

I hope that venerates solution to this problem

**Comment by eArabic** [comment]
http://arabico.ga/bolg/home/welcome

Author: محمد
Text : تجربة كتابة مقالة ... تجربة كتابة مقالة ...

Hosting a very slow free



On Dec 25, 2016, at 10:32 AM, redaxmedia <notifications@github.com> wrote:

Thank you for reporting. Please post the example wording here, so I can test again it.

**Comment by redaxmedia** [comment]
I thought about this issue for a while. For the moment a fix would break the whole security and therefore this is going to be a known bug.

**Comment by eArabic** [comment]
Thank you very much, what is the solution to this problem so I just apply them on my site, you show me the line of code that must change.

I understand that it hurts you security, but we have a problem that the writer can not write his name in Arabic.

Sorry for the mistakes I do not know the English language in writing or reading or translation.

**Comment by redaxmedia** [comment]
Just replace $specialFilter->sanitize with $htmlFilter->sanitize and it should work.

**Comment by eArabic** [comment]
Thank you very much, very excellent now works correctly ....

![32](https://cloud.githubusercontent.com/assets/24383546/21493195/4657d1d4-cc1b-11e6-88c7-d86f7cb66ae1.png)

**Comment by redaxmedia** [comment]
Great! How do you modify the template? Do you know how to use PostCSS? I did not write a howto yet.

**Comment by eArabic** [comment]
Thank you very much for editing on the file
default.min.css
Simple modification in color, font and orientation of the text to the right to suit the Arabic language

**Comment by redaxmedia** [comment]
**Never ever work on minified files.**

Redaxscript is made with PostCSS files (similar to SASS and LESS) that are composed, bundled to minified CSS files.

https://github.com/redaxmedia/redaxscript/tree/master/templates/default/assets/styles

Please do not work in the dist folders, they are generated using "grunt build-styles" described here:

https://redaxscript.com/documentation/assets/asset-builders
https://redaxscript.com/documentation/development/frontend-tools

**Comment by redaxmedia** [comment]
According to your problem, we do not plan to support RIGHT-TO-LEFT for the moment but you can open a new issue names "RTL support for default template" and we discuss it in the team.

BTW: Please do not extend issues, open new ones on the future.

**Comment by eArabic** [comment]
Thank you very much, I'm sorry and I apologize.
I do not know programming was the only test try, and did not mean to modify any files.
Sorry and thank you very much.

**Comment by redaxmedia** [comment]
There is no need to apologize, I just want to show you the correct way to do it.
