### ISSUE TITLE
No automatically alias generating in Arabic 

### ISSUE THREAD

**Issue by eArabic** [redaxmedia/redaxscript#478]
Hello
There is a problem in writing the article titles in English writes  Alias  automatically
The Arabic language is not handled and must be hand-writing and English

![00111](https://cloud.githubusercontent.com/assets/24383546/21494190/c3c2a4e6-cc20-11e6-9d91-68d8a9bd4621.png)

![00 00](https://cloud.githubusercontent.com/assets/24383546/21494192/c7a4602c-cc20-11e6-8541-e668c84b3f78.png)

**Comment by eArabic** [comment]
Thank you so much.

For example, these characters the Arabic language:
`ض ص ث ق ف غ ع ه خ ح ج د ط ك م ن ت ا ل ب ي س ش ظ ز و ة ى لا ر ؤ ء ئ لا أ إ`

Unicode:
`\u0636 \u0635 \u062b \u0642 \u0641 \u063a \u0639 \u0647 \u062e \u062d \u062c \u062f \u0637 \u0643 \u0645 \u0646 \u062a \u0627 \u0644 \u0628 \u064a \u0633 \u0634 \u0638 \u0632 \u0648 \u0629 \u0649 \u0644\u0627 \u0631 \u0624 \u0621 \u0626 \u0644\u0627 \u0623 \u0625`

How are added .
thank you very much ...

**Comment by redaxmedia** [comment]
I wrote above how to add it using the "th" as example...

**Comment by redaxmedia** [comment]
Hold on, I found a good library with massive support for all kind of languages. I try to rewrite the alias generator to use it: https://github.com/pid/speakingurl

**Comment by redaxmedia** [comment]
Great news, I implemented the library!
https://github.com/redaxmedia/redaxscript/pull/479/files

**Comment by eArabic** [comment]
Thank you very much, and sorry for the inconvenience and asking too many questions, I do not know programming, so I did not understand the change and now observed in the example in the previous participation.

I am very happy to have been the solution, I will wait for the new version and I hope that this problem is likely to work well.

Thank you very much with regards to you.

**Comment by redaxmedia** [comment]
Okay, I will release Beta4 in the new year.

![grafik](https://cloud.githubusercontent.com/assets/1835397/21500169/7584bbcc-cc3c-11e6-9110-88a14e579db2.png)

**Comment by eArabic** [comment]
Excellent Very, picture shows that the problem was solved, thank you very much
I will wait for the new version.
You Greetings
