### ISSUE TITLE
Question: nginx support

### ISSUE THREAD

**Issue by roddypratt** [redaxmedia/redaxscript#515]
The "features" list implies nginx support, but  I don't see any mention in the docs, or any way to configure this. Do you have an example nginx.conf  that implements the rewrites etc done in .htaccess?

**Comment by redaxmedia** [comment]
Hey,

some users successfully tested Redaxscript on nginx using a `.htaccess` converter: https://timmehosting.de/htaccess-converter

I will add this to the documentation as soon as possible. Looks like you are new to GitHub, consider to give Redaxscript a star if you like the project.

Best regards
Henry

**Comment by redaxmedia** [comment]
Done https://github.com/redaxmedia/redaxscript-documentation/commit/9776ad50edeff3ba86a1c8247cbd675019acf6d0

**Comment by roddypratt** [comment]
Much appreciated, Thanks!

**Comment by redaxmedia** [comment]
Glad that I could help - the live docs are updated now.
