### ISSUE TITLE
Bug with TinyMCE editor 

### ISSUE THREAD

**Issue by KonstantinFromRussia** [redaxmedia/redaxscript#535]
Hello!
When I select the full screen of the editor - the menu of your system overlaps the menu of the editor

![redax6](https://user-images.githubusercontent.com/31459888/29933423-3bd8f9d6-8e80-11e7-8d2d-68bbe715edb0.jpg)

**Comment by redaxmedia** [comment]
Thank you for reporting.

Have you tried to adjust the z-index of the editor inside [skin.css](https://github.com/redaxmedia/redaxscript/blob/master/modules/Tinymce/assets/styles/skin/skin.css)?

**Comment by KonstantinFromRussia** [comment]
I apologize, but I assumed that the error will be corrected by the one who created the plugin.
If it is not so - then again I apologize, but I can not figure out how to do it :(

**Comment by redaxmedia** [comment]
Solved via https://github.com/redaxmedia/redaxscript/commit/8888cbd76c62360ccce8eaed03ec9863858bb2ce
