### ISSUE TITLE
Increase security of hashed passwords

### ISSUE THREAD

**Issue by vv01f** [redaxmedia/redaxscript#91]
SHA1 is not much better than MD5 right now. The reference implementation lacks security for stored passwords on this current path.
My suggestion is to replace it with bcrypt for having rounds and easier replaceability of hash algorithms in future.

- split off pwd handling from reset-form etc.
- abondon sha1 and hash-specific implementation
- use bcrypt
- add configuration option for rounds (could be special for user groups)
- add configuration option for hash to be used - standard should be whirlpool/blowfish
- add user defined salt (pseudorandom)
- add user defined salt and bind email address to password (some hash of email, e.g. sha512)
- take care of change email address feature

advantages:
* brute forcing and rainbow tables are much less effective
* upgrading hash algo is easy. just change the option
* current algo and rounds are defined in db as salt is

**Comment by redaxmedia** [comment]
Reopen - we have a Hash class now that can handle this!

**Comment by redaxmedia** [comment]
Redaxscript is now using <code>password_hash</code> and <code>password_verify</code> for the very best password security. PHP version lower than 5.5 fallback to sha512 and salt from config file.
